void main()
	try
		raise(new Exception("test"))
	except Exception as e
		print(e.message())

